name: Test
on:
  push:
    branches:
      - "*"
    paths:
    - '**/*.go'
  pull_request:
    paths:
    - '**/*.go'
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run tests
        run: |
          make test
